### ISSUE TITLE
phone number does not seem to be stored

### ISSUE THREAD

**Issue by onno-schuit** [andresmrg/auth_twofactor#1]
After providing a username and password I get to see the prompt to fill in my phone number. After inputting the phone number and confirming, I'm redirected to the login screen.

Upon reentering my username and password, I am redirect to the screen with the phone number prompt for again.

Probably unrelated:

Notice: Undefined offset: 1 in /mnt/9666713C66711DE5/php/lidl/public_html/auth/twofactor/auth.php on line 124

**Comment by andresmrg** [comment]
Onno, I have updated the code with the commit 77596ee , that should fix the issue, please test and let me know.
