### ISSUE TITLE
Where to input temp password & personnel number?

### ISSUE THREAD

**Issue by onno-schuit** [andresmrg/auth_twofactor#2]
What's the access point for inputting my temp password and personnel number? This is the part of the flow chart following the "Registered?" > "No" branch.

**Comment by andresmrg** [comment]
If the user is not registered, we understand Lidl would create the user account using the tool Upload User using CSV where there they can put a temporary password to each user. Once this is done, users will receive an email with the temp password and can use these login details to log in to the normal login page. Consider this Use case 1.

Use case 2: Enable self-registration where a user can create their own account. This doesn't apply to the temporary password but would this be even a case? If it is, we should recommend creating a user profile field so a user's phone number is required on the signup form. The Two authentication plugin would play the same role, after user signup, it will validate the IP range and the phone number and take the user to the validation pages if they must validate any data (code or phone).

Let me know your thoughts.
